language: go

go: 1.13.x

# Cron jobs push tags, don't insta-rebuild after a cron task
branches:
  only:
  - master

services:
  - docker

install: true

before_script:
  # Configure the SSH key to pull and push the repository
  - echo $GITHUB_PUSH_KEY | base64

script:
  # Everything seems ok, push the master branch back to GitHub
